# Generated by Django 5.1.4 on 2025-02-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uservisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVisit',
        ),
    ]
